### PR TITLE
WEB-879 Chore: Add Linting to CI Pipeline

### PR DESCRIPTION
**Pull request by samwise-repo1**
Mobile-first responsive design has been implemented to enhance user experience on mobile devices.

### CODE REVIEW

**Review by frodo-repo — COMMENTED** [review]
This hardcoded value might be better suited as a constant at the top of the file.

**Review by samwise-repo1 — COMMENTED** [review]
The CSS rules here seem to be redundant. Can you please review and remove unnecessary ones?

**Review by samwise-repo1 — COMMENTED** [review]
Really good job with this regex. It covers all the cases we discussed.

**Review by samwise-repo1 — COMMENTED** [review]
I appreciate how well-structured and clean your code is. It's very easy to follow!

**Review by frodo-repo — COMMENTED** [review]
Excellent use of destructuring here, it makes the code much cleaner.

**Review by frodo-repo — CHANGES_REQUESTED** [review]
This logic might be clearer if you used a switch statement instead of multiple if-else statements.

**Review by frodo-repo — CHANGES_REQUESTED** [review]
There seems to be a typo in the function name. Did you mean `calculateAverage` instead of `calculateAverge`?

**Review by frodo-repo — APPROVED** [review]
I'm a bit concerned about the potential performance impact of this loop. Have you thought about optimizing it?

**Review by frodo-repo — CHANGES_REQUESTED** [review]
I'm impressed with your use of design patterns here, it really enhances the code organization.

**Pull request closed without merging**
